services:
  - type: web
    name: bg-remover-app
    runtime: node
    buildCommand: |
      npm install
      pip install -r requirements.txt
    startCommand: node server.js
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
    plan: free
